config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: redirect('/items')
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :price, numericality: { greater_than: 0 }
  validates :name, presence: true

  after_initialize { p 'initialize' }
  after_save { p 'save' }
  after_create { p 'create' }
  after_update { p 'update' }
  after_destroy { p 'destroy' }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout false
  skip_before_action :verify_authenticity_token

  def index
    @items = Item.all
  end

  def create
    item = Item.create(items_params)
    if item.persisted?
      redirect_to items_path
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  def new
    
  end

  def show
    @item = find_item_by_id(params[:id])
  end

  def edit
    @item = find_item_by_id(params[:id])
  end

  def update
    item = find_item_by_id(params[:id])

    if item.update(items_params)
      redirect_to item_path
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    item = find_item_by_id(params[:id])
    item.destroy

    if item.destroyed?
      redirect_to items_path
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  private
  def items_params
    params.permit(:name, :price)
  end

  def find_item_by_id(id)
    begin
      Item.find_by!(id: id)
    rescue ActiveRecord::RecordNotFound
      render body: "Page not found", status: 404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h2 style="color: #B00100; margin: 0 auto">Edit item <%= @item.name %></h2>

<%= form_tag item_path(@item), method: :put do %>
  <%= label_tag :name %>
  <%= text_field_tag :name, @item.name %>
  <%= label_tag :price %>
  <%= text_field_tag :price, @item.price %>
  <%= submit_tag "Update", class: "btn btn-large btn-primary" %>
<% end %>

app/views/items/index.html.erb
<h2 style="color: #B00100; margin: 0 auto">All items</h2>

<% @items.each do |item| %>
  <ul>
    <li># <%= item.id %></li>
    <li>Name: <%= link_to item.name, item %></li>
    <li>Price: <%= item.price %> $</li>
    <li>Description: <%= item.description %></li>
    <li>Weight: <%= item.weight %></li>
    <li><%= button_to "delete", item_path(item), method: :delete %></li>
  </ul>
<% end %>

<br />

<%= link_to "new item", new_item_path %> 

app/views/items/new.html.erb
<h2 style="color: #B00100; margin: 0 auto">Create new item</h2>

<%= form_tag items_path, method: :post do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= label_tag :price %>
  <%= text_field_tag :price %>
  <%= submit_tag "Save", class: "btn btn-large btn-primary" %>
<% end %>

app/views/items/show.html.erb
<h2 style="color: #B00100; margin: 0 auto">Show item</h2>

<h4><%= @item.name %></h4>

<ul>
  <li>Price: <%= @item.price %> $</li>
  <li>Description: <%= @item.description %></li>
  <li>Weight: <%= @item.weight %></li>
</ul>

<br />

<p>Links:</p>
<%= link_to "Edit #{@item.name}", edit_item_path %><br />
<%= button_to "Delete #{@item.name}", item_path(@item), method: :delete %><br />
<%= link_to "Index", edit_item_path %><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSunTutorial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>